name: hello
on: push
env:
  TOP: Top env
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.run_id }}
      - run: echo foo
        if : ${{ contains(github.run_id, 's')}}
